
// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;

namespace MLModel1_ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            var messages = File.ReadAllLines("C:\\projects\\C\\ML_NET_START\\ML_NET_START\\MLModel1_ConsoleApp2\\messages.txt");
            foreach(var message in messages)
            {
                MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
                {
                    Message = message,
                };

                var predictionResult = MLModel1.Predict(sampleData);
                Console.WriteLine($"Spam: {predictionResult.Prediction.ToString()} Message: {message}");
            }
            


            /*Console.WriteLine($"\n\nPredicted Spam: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();*/
        }
    }
}
